feat!: use ESTree `directive` property when searching for `"use strict"`
eslint/eslint-scope pull request #118
Opened 2024-01-03 19:03 UTC by mdjermanovic

Fixes #117

Updates the code that searches for `"use strict"` directives to use the [`directive` property](https://github.com/estree/estree/blob/master/es5.md#directive) as the only way to determine whether a node represents a directive. All other ways are dropped, as it is expected that the given AST follows the ESTree Spec.

Option `directive` that was enabling the use of non-standard DirectiveStatement nodes is also dropped.

2024-01-03 19:13 UTC, nzakas requested changes
The changes look good to me. Can you add a couple tests with `"use strict"` inside of a function just to cover our bases?

2024-01-03 20:04 UTC, mdjermanovic commented
I've added equivalent tests with function now.

2024-01-04 09:20 UTC, snitin315 approved these changes
LGTM, thanks!

I'll leave it open for @nzakas

2024-01-04 18:20 UTC, nzakas approved these changes
LGTM.

2024-01-04 18:20 UTC, merged